version: '3.5'
services:
  stubby4j-jre11:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./data:/home/stubby4j/data"
    ports:
      - 8884:8884
    environment:
      YAML_CONFIG: main.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8884
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
